goal_x10 = [7, 5]
map_reward_x10 = [
    [
        0,
        -10,
        0,
        0,
        0,
        -10,
        0,
        -10,
        0,
        0,
    ],
    [
        0,
        0,
        0,
        -10,
        0,
        -10,
        0,
        -10,
        0,
        -10,
    ],
    [
        0,
        -10,
        -10,
        0,
        0,
        -10,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        -10,
        -10,
        0,
        0,
        0,
        -10,
        0,
        -10,
    ],
    [
        -10,
        0,
        0,
        0,
        -10,
        0,
        -10,
        0,
        0,
        -10,
    ],
    [
        -10,
        0,
        -10,
        0,
        -10,
        -10,
        -10,
        0,
        -10,
        -10,
    ],
    [
        -10,
        0,
        0,
        -10,
        0,
        1,
        -10,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        -10,
        -10,
        -10,
        0,
        -10,
        0,
        -10,
        0,
    ],
    [
        -10,
        0,
        0,
        -10,
        0,
        0,
        0,
        -10,
        0,
        0,
    ],
    [
        0,
        0,
        -10,
        0,
        0,
        -10,
        0,
        0,
        0,
        -10,
    ],
]

map_reward_x5 = [
    [
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        -10,
        -10,
        0,
        0,
    ],
    [
        0,
        0,
        -10,
        0,
        0,
    ],
    [
        0,
        -10,
        1,
        -10,
        0,
    ],
    [
        0,
        -10,
        0,
        0,
        0,
    ],
]
goal_x5 = [3, 2]
